from typing import Any, Dict

from selenium.webdriver.firefox.options import Options

class Firefox:
    def __init__(self, options: Options, seleniumwire_options: Dict[str, Any]) -> None: ...
    def get_full_page_screenshot_as_base64(self) -> str: ...
    def get(self, url: str) -> None: ...
    def quit(self) -> None: ...
    @property
    def har(self) -> str: ...
